// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RepositoryAnalyzer.Data;

#nullable disable

namespace RepositoryAnalyzer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RepositoryAnalyzer.Models.Assembly", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AssemblyFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OutputType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectFilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProjectStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("TargetFramework")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("UniqueIdentifier");

                    b.ToTable("Assemblies");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.AssemblyDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<int>("SourceAssemblyId")
                        .HasColumnType("int");

                    b.Property<int>("TargetAssemblyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("SourceAssemblyId");

                    b.HasIndex("TargetAssemblyId");

                    b.ToTable("AssemblyDependencies");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Dependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceProjectId")
                        .HasColumnType("int");

                    b.Property<int?>("SourceSolutionId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TargetProjectId")
                        .HasColumnType("int");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("SourceProjectId");

                    b.HasIndex("SourceSolutionId");

                    b.HasIndex("TargetProjectId");

                    b.ToTable("Dependencies");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GuidDeterminationMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumberOfReferencedProjects")
                        .HasColumnType("int");

                    b.Property<string>("ProjectStyle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("TargetFramework")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("UniqueIdentifier");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Scan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GitCommitHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RepositoryPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ScanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ShortCommitHash")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("ScanDate");

                    b.ToTable("Scans");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Solution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("GuidDeterminationMethod")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsSingleProjectSolution")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("NumberOfReferencedProjects")
                        .HasColumnType("int");

                    b.Property<int>("ScanId")
                        .HasColumnType("int");

                    b.Property<string>("UniqueIdentifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VisualStudioGuid")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ScanId");

                    b.HasIndex("UniqueIdentifier");

                    b.ToTable("Solutions");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Assembly", b =>
                {
                    b.HasOne("RepositoryAnalyzer.Models.Scan", "Scan")
                        .WithMany("Assemblies")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.AssemblyDependency", b =>
                {
                    b.HasOne("RepositoryAnalyzer.Models.Assembly", "SourceAssembly")
                        .WithMany("DependenciesFrom")
                        .HasForeignKey("SourceAssemblyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RepositoryAnalyzer.Models.Assembly", "TargetAssembly")
                        .WithMany("DependenciesTo")
                        .HasForeignKey("TargetAssemblyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceAssembly");

                    b.Navigation("TargetAssembly");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Dependency", b =>
                {
                    b.HasOne("RepositoryAnalyzer.Models.Project", "SourceProject")
                        .WithMany("DependenciesFrom")
                        .HasForeignKey("SourceProjectId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RepositoryAnalyzer.Models.Solution", "SourceSolution")
                        .WithMany("DependenciesFrom")
                        .HasForeignKey("SourceSolutionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("RepositoryAnalyzer.Models.Project", "TargetProject")
                        .WithMany("DependenciesTo")
                        .HasForeignKey("TargetProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceProject");

                    b.Navigation("SourceSolution");

                    b.Navigation("TargetProject");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Project", b =>
                {
                    b.HasOne("RepositoryAnalyzer.Models.Scan", "Scan")
                        .WithMany("Projects")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Solution", b =>
                {
                    b.HasOne("RepositoryAnalyzer.Models.Scan", "Scan")
                        .WithMany("Solutions")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Assembly", b =>
                {
                    b.Navigation("DependenciesFrom");

                    b.Navigation("DependenciesTo");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Project", b =>
                {
                    b.Navigation("DependenciesFrom");

                    b.Navigation("DependenciesTo");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Scan", b =>
                {
                    b.Navigation("Assemblies");

                    b.Navigation("Projects");

                    b.Navigation("Solutions");
                });

            modelBuilder.Entity("RepositoryAnalyzer.Models.Solution", b =>
                {
                    b.Navigation("DependenciesFrom");
                });
#pragma warning restore 612, 618
        }
    }
}
